<a href="https://colab.research.google.com/github/Pradeep4629/FMML-LAB/blob/main/FMML_2023_Basics_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started

FMML Module 1, Lab 1 <br>
 Module Coordinator: Amit Pandey ( amit.pandey@research.iiit.ac.in ) <br>
 Release date: Aug 2022 <br>



### In this notebook we will be covering the very basics of Python and some basic libraries such as Numpy, Matplotlib and Nltk.
#### It is suggested that you go through each line and try some examples.

#### Section 1 - Python : Basic data types and indexing.

In [ ]:
## Strings
'''
A string is a collection of one or more characters put in a single quote,
 double-quote or triple quote. In python there is no character data type,
 a character is a string of length one. It is represented by str class.

String can have special characters. String can be indexed

'''


name = 'First Lab'
name_extended = name + 'Module 1'
last_element_string = name[-1] # -1 in python is index of the last element.
## indexing is important for preprocessing of the raw data.

In [ ]:
print(name ,"\n", name_extended, "\n", last_element_string)

First Lab 
 First LabModule 1 
 b


In [ ]:
## List

'''
Lists are ordered collection of data, and are very similar to arrays,
It is very flexible as the items in a list do not need to be of the same type.
'''

name_list = ['First Lab', 3 , '1.1' , 'Lab 1'] ## notice elements are of different data type.
name_list.extend(['Module 1']) ## adding elements to list (Read about append method as well).
element_2 = name_list[1] ## Just like other languages, the index starts from 0.
two_dimesional_list = [[1,2],[3,4]] ## practice with multi-dimensional lists and arrays
## you would soon be required to handle 4 dimensional data :p :)
name_list[2] = '1.111' ##list elements can be changed

In [ ]:
print(name_list)
print(element_2)
print(two_dimesional_list)
## list can have list, dictionary, string etc.

['First Lab', 3, '1.111', 'Lab 1', 'Module 1']
3
[[1, 2], [3, 4]]


In [ ]:
## Tuples

name_tuple = ('First Lab', 1, (2,3),[1,1,'list having string']) ## A tuple can have a tuple.

print(name_tuple[2])
print("first indexing the last element of the tuple, which is a list and \n then last element of the list (a string) and then second last element of the string:")
print(name_tuple[-1][-1][-2])


(2, 3)
first indexing the last element of the tuple, which is a list and 
 then last element of the list (a string) and then second last element of the string:
n


In [ ]:
## tuples are immutable, read the error !
 #usued when passing parameters etc. and dont want them to be changed

name_tuple[1] = 2

TypeError: ignored

In [ ]:
## Sets
'''a Set is an unordered collection of data types that is iterable, mutable and has no duplicate elements.
The order of elements in a set is undefined though it may consist of various elements.
The major advantage of using a set, as opposed to a list,
 is that it has a highly optimized method for checking whether a specific element is contained in the set.
'''
set_unique = set([1,1,2,3,5,6,'Lab1'])
print(set_unique) ##notice it is unordered
last_el = set_unique.pop()
set_unique.add((1,2))


print(last_el)
print(set_unique)






{1, 2, 3, 5, 6, 'Lab1'}
1
{2, 3, (1, 2), 5, 6, 'Lab1'}


In [ ]:
set_unique[1] ##it is not indexable

TypeError: ignored

In [ ]:
## Dictionary
'''
Dictionary in Python is an unordered collection of data values, used to store data values like a map,
 which, unlike other data types which hold only a single value as an element.
'''

dic = {'1': 'A','2':'B', 'C':3 } ##Observe how key and values can be anything
dic['4'] ='New'
print(dic)

#### Question 0:
###### write down 3-5 methods applicable to each data type. (Hint: extend, reverse, etc.

In [ ]:
# list
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)

my_list.insert(1,5)
print(my_list)

pop_element = my_list.pop()
print(pop_element)

In [ ]:
# String
string = "hello world"
length = len(string)
print(length)

substring = string [0:5]
print(substring)

str1="hello"
str2= "world"
str3= str1+str2
print(str3)

In [ ]:
#Dictionary

my_dict = {'name': 'sai', 'age': 30}
name = my_dict.get('name')
print(name)  # Output: 'John'

keys = my_dict.keys()
print(keys)  # Output: dict_keys(['name', 'age'])

values = my_dict.values()
print(values)

In [ ]:
#sets

my_set = {1, 2, 3, 4, 5}
another_set = {3, 4, 5, 6, 7}

my_set.add(6)
print(my_set)

my_set.remove(3)
print(my_set)

my_set.clear()
print(my_set)

In [ ]:
#Turple

my_tuple = (1, 2, 3, 4, 5)
first_element = my_tuple[0]
print(first_element)

sliced_tuple = my_tuple[1:4]
print(sliced_tuple)

a, b, c, d, e = my_tuple
print(a, b, c, d, e)

## Section 2 - Functions
### a group of related statements that performs a specific task.

In [ ]:
def add_new(a:str, b): ## a and b are the arguments that are passed. to provide data type hint
                              # def add_new(x: float, y: float) -> float:
  sum = a + b
  return sum

ans = add_new(1,2) ## intentionally written str, and passed int, to show it doesn't matter. It is just hint
print(ans)

In [ ]:
asn = add_new()

In [ ]:
def check_even_list(num_list):

    even_numbers = []

    # Go through each number
    for number in num_list:
        # Once we get a "hit" on an even number, we append the even number
        if number % 2 == 0:
            even_numbers.append(number)
        # Don't do anything if its not even
        else:
            pass
    # Notice the indentation! This ensures we run through the entire for loop
    return even_numbers

#### Question 1 :

##### Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.


#### Question 2 :
##### Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.

##### work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]

##### Answer : the female worker that worked the most hours is Penny and she should be paid 18400

In [ ]:
# Question 1
def revadd(a,b):
  return a[::-1] + b

print(revadd("Hi", " Hello"))

iH Hello


In [ ]:
# Question 2
def work(hours):
  females = [i for i in hours if i[-1] == "F"]
  max_hour = max([i[1] for i in females])
  res = [i for i in females if i[1] == max_hour]
  return f"the female worker that worked the most hours is {res[0][0]} and she should be paid {res[0][1]*20}"

hours =  [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
print(work(hours))

the female worker that worked the most hours is Penny and she should be paid 18400


#### Section 3 - Libraries and Reading data.

##### Numpy - One of the most used libraries - supports for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [ ]:
import numpy as np

In [ ]:

a = np.array([1,1,2,3,4,5,5,6,1]) ## np.array converts given list to array

b = a>1 ## important comparison operation, where frequently used in manipulation and image processing.

print(b)
print(a[b]) ## [printing only those values in a which are greater than 1]


[False False  True  True  True  True  True  True False]
[2 3 4 5 5 6]


In [ ]:
a_range = np.arange(10,19).reshape(3,3) ## create a 3x3 array with values in range 10-19
a_range


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
## Indexing in arrays works same as that of list

a_range[0] # printing all the columns of first row

array([10, 11, 12])

In [ ]:
a_range[:,2] #printing all the rows of second column

array([12, 15, 18])

In [ ]:
iden = np.eye(3) #idnetity matrix of given size
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## adding two matrices
summed = a_range + iden
summed


array([[11., 11., 12.],
       [13., 15., 15.],
       [16., 17., 19.]])

In [ ]:
### arrays support normal matrix multiplication that you are used to, point-wise multiplication
### and dot product as well.

mul = a_range@iden ## normal multiplication
mul


array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [ ]:
## point wise multiplication
p_mul = a_range * iden
p_mul

In [ ]:
## Transpose of a matrix.

mtx_t = mul.T
mtx_t


In [ ]:
### Here we are changing the values of last row of the transposed matrix.
### basically point wise multiplying the values of last row with 1,2 and 3

mtx_t[2] = mtx_t[2]*[1,2,3] ## indexing, point wise multiplication and mutation of values
mtx_t

In [ ]:
## Just like the greater than 1 (a>1) example we saw earlier.
## here we are checking if the elements are divisible by 2 (%), and if they are, then replace by 0.

mtx_t[(mtx_t % 2 == 0)] = 0 ## convert even elements of the matrix to zero.
mtx_t

#### Question 3 :

##### a)Create a 5x5 matrix of the following form,

##### [[1,1]
#####  [2,2]]

#####  i.e. each row is increasing and has repetive elements.

######  Hint : you can use hstack, vstack  etc.

##### b) find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix)

In [ ]:
a = np.vstack(np.arange(1,6))
matrix = np.hstack([a]*5)
matrix

In [ ]:
a = np.vstack(np.arange(1,6))
b = np.vstack(np.arange(6,11))
mat1 = np.hstack([a]*5)
mat2 = np.hstack([b]*5)
print(mat1)
print(mat2)
print(mat1 @ mat2)

#### Reading Files

In [ ]:
## loading from the google drive
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
with open ('/content/sample_data/README.md', 'r') as f:
  a = f.readlines()

a ## here a is list of elements/strings each splitted at \n, \n is also part of the list element.


In [ ]:
import pandas as pd

df = pd.read_csv('/content/sample_data/california_housing_test.csv','r')
df.head(10) ## pass as argument number of top elements you wish to print. Head is used to have a quick glance and understand the data.

In [ ]:
len(df.columns), df.columns

In [ ]:
df.columns[0]

In [ ]:
df['longitude,"latitude","housing_median_age","total_'][:5]

In [ ]:
df = df.rename(columns = {'longitude,"latitude","housing_median_age","total_':'Detail1'}) ##rename column names as at times it makes it easier for us

In [ ]:
df.head(3)

In [ ]:
df.iloc[:5, 0]  ##iloc - index - 0 to 4 rows and first column only.

In [ ]:
import matplotlib
from matplotlib import pyplot as plt

In [ ]:
xpoints = np.array([1, 8])
ypoints = np.array([3, 10])

plt.plot(xpoints, ypoints)
plt.show()

In [ ]:
xpoints = np.array([1, 2, 6, 8])
ypoints = np.array([3, 8, 1, 10])

plt.plot(xpoints, ypoints)
plt.show()

## Creating a dataframe.
#### Task: Study about other methods of creating dataframe (for example: using Pandas Series, Lists etc.)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
values = np.arange(16).reshape(4,4)
values

In [ ]:
dataframe_from_array = pd.DataFrame(values, index = ['a','b','c','d'], columns=['w','x','y','z'] )
dataframe_from_array

In [ ]:
dataframe_from_array.loc[['a','b'],['w','x']]

In [ ]:
dataframe_from_array.iloc['a'] ## it needs position as integer

In [ ]:
dataframe_from_array.iloc[1,3] #second row and last column

In [ ]:
dataframe_from_array.iloc[::2,::2]

In [ ]:

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 200), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

In [ ]:
## Question 3 : Upload an image to your google drive, Use plt.imread to read image from the google drive and then print that image using plt.imshow


## Answer 3 :
file_path = '/content/gdrive/MyDrive/Documents/img.png'
img = plt.imread(file_path)
plt.imshow(img)

## 1) make sure drive is loaded and then upload a test image onto your drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')